server {
    listen 80;
    listen [::]:80;
    server_name __DOMAIN__ __WWW_DOMAIN__;

    root __WEB_ROOT__;
    index index.html;

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location /data/ {
        expires 1h;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;
}
